-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg7Mmr9JPXAqx2KM89IhaxLMEiqnxdDQ2OGbGbi6rUkKSgCgYIKoZIzj0DAQehRANCAAQGIBE4L2ZvVyds6JnZzb61MRJXQ3zuZpLymXc3sLZR/RoYuh+/NwCoZmlRRb2cvZt3yJ6S6OdbLPsXZFxZE81V
-----END PRIVATE KEY-----